#!/usr/bin/bash

# scre
# Screenshot utility by Dmitry Kudriavtsev

# Settings

# The path to store the screenshots locally.
localpath=~/Pictures/Screenshots

# The server that the images will be scp'd to.
server='image-upload@dk0.us'

# The path on the server to put the images.
serverpath='/var/www/files/screenshots'

# Retrieve the name of the current active program.
#program=$(xprop -id $(xdotool getactivewindow) | grep WM_CLASS | sed -n 's/^.*"\(.*\)",.*$/\1/p')

# Format the date in your desired format.
date=$(date +'%Y-%m-%d_%H-%M-%S')

# The final filename that will be stored/copied.
#filename="$program"-"$date".png
#filename=$(dd if=/dev/urandom bs=1 count=3 | base64).png
filename=$RANDOM.png
filename_base="${filename%.*}"
filename_full="$localpath"/"$filename"

# The prefix to the URLs that the images will have when uploaded.
#url_prefix="http://s.dk0.us"
#baseurl='http://NAME.dk0.us'
baseurl='http://s.dk0.us/NAME.png'

# The sound played after a successful upload.
sound=~/bin/TaskCompletedSound.wav

# The script.

# Fail on errors
#set -e

# Function to encode a URL.
urlencode() {
  local string="${1}"
  local strlen=${#string}
  local encoded=""
  local pos c o

  for (( pos=0 ; pos<strlen ; pos++ )); do
     c=${string:$pos:1}
     case "$c" in
        [-_.~a-zA-Z0-9] ) o="${c}" ;;
        * )               printf -v o '%%%02x' "'$c"
     esac
     encoded+="${o}"
  done
  echo -n "${encoded}"
}

# The final URL, with encoded image name.
#url="$url_prefix"/$(urlencode "$filename_base")
url=$(echo $baseurl | sed s/NAME/$(urlencode "$filename_base")/)

# Take the screenshot, save to the correct path, copy it to the clipboard.
maim -s --hidecursor | tee "$filename_full" | xclip -sel clip -t image/png && \
  notify-send -i "$filename_full" "Screenshot taken." "$filename_full" 

# Copy the image to the server using scp. If successful:
  # Overwrite the clipboard (currently containing image) with the image's URL.
  # Play the success sound.
  # Notify of successful screenshot.
scp -q "$localpath"/"$filename" "$server":"$serverpath"/"$filename" && \
  notify-send -i "$filename_full" "Screenshot uploaded." "URL copied to clipboard." && \
  echo -n "$url" | xclip -sel clip && \
  aplay "$sound"
